name: MineZReloaded-Core
main: de.jefa.core.CorePlatformPlugin
version: ${project.version}
api-version: "1.21"
load: STARTUP
authors: [ "de.jefa"]
description: "Core services for MineZ Reloaded (config, events, scheduler)"
commands:
  mzreload:
    description: Reload MineZ configs
    permission: minez.admin.reload
permissions:
  minez.admin.reload:
    default: op